dataset_conf:
  batch_conf:
    batch_size: 256
  context_expansion: true
  context_expansion_conf:
    left: 2
    right: 2
  feature_extraction_conf:
    dither: 1.0
    feature_type: fbank
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
  filter_conf:
    max_length: 2048
    min_length: 0
  frame_skip: 3
  resample_conf:
    resample_rate: 16000
  shuffle: true
  shuffle_conf:
    shuffle_size: 1500
  spec_aug: true
  spec_aug_conf:
    max_f: 10
    max_t: 20
    num_f_mask: 1
    num_t_mask: 1
  speed_perturb: false
model:
  activation:
    type: identity
  backbone:
    input_affine_dim: 140
    left_order: 10
    left_stride: 1
    linear_dim: 250
    num_layers: 4
    output_affine_dim: 140
    proj_dim: 128
    right_order: 2
    right_stride: 1
    type: fsmn
  classifier:
    dropout: 0.1
    type: identity
  cmvn:
    cmvn_file: model/global_cmvn.kaldi
    norm_var: true
  hidden_dim: 128
  input_dim: 400
  output_dim: 2599
  preprocessing:
    type: none
optim: adam
optim_conf:
  lr: 0.001
  weight_decay: 0.0001
training_config:
  criterion: ctc
  grad_clip: 5
  log_interval: 10
  max_epoch: 80
